### ISSUE TITLE
Can you please write instructions to run the code?

### ISSUE THREAD

**Issue by lvu213120315** [Rikpat/purevpnwg#1]

**Comment by lvu213120315** [comment]
I get an error when running the code
'no tokens in cookies'

**Comment by Rikpat** [comment]
yes, the cookie part is sometimes not working, try running the cli with *full* command, `purevpnwg full`. 

This runs the whole process in a single command but doesn't persist any cookies for subsequent runs, so you have to provide your password everytime (the cookies were there to prevent having to log-in everytime or storing password in env vars). 

I'm running it in kubernetes cluster so my password is in a kubernetes secret.

**Comment by Rikpat** [comment]
I've written simple instructions on how to run this locally
